Repository googleapis/nodejs-kms, pull requests merged in 2019-05, with the labels that each got.

#150 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#151 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#152 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#154 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: automerge, cla: yes

#156 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#155 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: automerge, cla: yes

#147 fix: indicate that Encrypt, Decrypt, AsymmetricDecrypt, AsymmetricSign are idempotent, such that they're retried
  src/v1/key_management_service_client_config.json
  synth.metadata
Labels: :rotating_light:, cla: yes

#157 fix: DEADLINE_EXCEEDED is no longer retried
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/doc/google/type/doc_expr.js
  src/v1/key_management_service_client.js
  src/v1/key_management_service_client_config.json
  synth.metadata
Labels: cla: yes

#159 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/key_management_service_client_config.json
  synth.metadata
Labels: cla: yes

#160 refactor: update metadata, synth, and deps
  .cloud-repo-tools.json
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .gitignore
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/system-test/.eslintrc.yml
  src/v1/doc/google/protobuf/doc_timestamp.js
  synth.metadata
  synth.py
  system-test/.eslintrc.yml
  test/.eslintrc.yml
  test/mocha.opts
Labels: cla: yes

#162 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#166 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#167 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/key_management_service_client.js
  synth.metadata
Labels: cla: yes

#168 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#169 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#170 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#171 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
