Repository googleapis/nodejs-kms, pull requests merged in 2019-06, with the labels that each got.

#173 feat: support apiEndpoint override in client constructor
  src/v1/key_management_service_client.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#174 chore: release 1.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#176 docs: update return type in jsdoc for Buffers
  src/v1/doc/google/cloud/kms/v1/doc_resources.js
  src/v1/doc/google/cloud/kms/v1/doc_service.js
  src/v1/key_management_service_client.js
  synth.metadata
Labels: cla: yes

#177 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#178 chore: release 1.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#180 feat: introduces CreateImportJob, ListImportJob, GetImportJob
  package.json
  protos/google/cloud/kms/v1/resources.proto
  protos/google/cloud/kms/v1/service.proto
  samples/disableCryptoKeyVersion.js
  samples/enableCryptoKeyVersion.js
  src/v1/doc/google/cloud/kms/v1/doc_resources.js
  src/v1/doc/google/cloud/kms/v1/doc_service.js
  src/v1/key_management_service_client.js
  src/v1/key_management_service_client_config.json
  synth.metadata
  test/gapic-v1.js
Labels: :rotating_light:, cla: yes

#181 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#182 chore: release 1.2.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#183 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#184 chore: release 1.2.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process
