Repository googleapis/nodejs-kms, pull requests merged in 2019-01, with the labels that each got.

#103 fix(docs): remove unused IAM message types
  src/v1/doc/google/iam/v1/doc_iam_policy.js
  src/v1/doc/google/iam/v1/doc_policy.js
  synth.metadata
Labels: cla: yes

#102 build: check broken links in generated docs
  .jsdoc.js
  .kokoro/docs.sh
  README.md
  package.json
  src/index.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  synth.py
Labels: cla: yes

#106 Release @google-cloud/kms v0.3.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#107 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  src/v1/doc/google/cloud/kms/v1/doc_resources.js
  src/v1/doc/google/cloud/kms/v1/doc_service.js
  src/v1/doc/google/iam/v1/doc_iam_policy.js
  src/v1/doc/google/iam/v1/doc_policy.js
  src/v1/doc/google/protobuf/doc_duration.js
  src/v1/doc/google/protobuf/doc_field_mask.js
  src/v1/doc/google/protobuf/doc_timestamp.js
  src/v1/index.js
  src/v1/key_management_service_client.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#108 build: ignore googleapis.com in doc link checker
  .kokoro/docs.sh
Labels: automerge, cla: yes
