Repository googleapis/nodejs-kms, pull requests merged in 2019-07, with the labels that each got.

#186 feat: add IAM Policy Options
  src/v1/doc/google/iam/v1/doc_options.js
  src/v1/key_management_service_client.js
  synth.metadata
Labels: cla: yes

#187 chore: release 1.3.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#185 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: automerge, cla: yes

#190 docs: use the jsdoc-fresh theme
  .jsdoc.js
  package.json
Labels: cla: yes

#191 docs: document apiEndpoint over servicePath
  src/v1/key_management_service_client.js
Labels: cla: yes
