Repository googleapis/nodejs-kms, pull requests merged in 2020-07, with the labels that each got.

#352 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#353 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#355 typeo: typeo in .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#357 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#358 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#363 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#364 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#365 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#362 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#366 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#367 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#368 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none
