Repository googleapis/nodejs-kms, pull requests merged in 2020-06, with the labels that each got.

#336 fix: update common protos and fix synth
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
  synth.py
Labels: cla: yes

#338 fix: samples-test script
  package.json
Labels: automerge, cla: yes

#341 [CHANGE ME] Re-generated to pick up changes from self.
  protos/protos.js
  src/v1/key_management_service_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: none

#343 feat(secrets): begin migration to secret manager from keystore
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#345 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#346 fix: handle fallback option properly
  src/v1/key_management_service_client.ts
  synth.metadata
Labels: cla: yes, context: none

#349 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#348 docs: change relative URLs to absolute URLs to fix broken links.
  protos/google/cloud/kms/v1/resources.proto
  synth.metadata
Labels: cla: yes, context: full

#350 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full
