Repository googleapis/nodejs-kms, pull requests merged in 2020-05, with the labels that each got.

#328 chore: update UUID to latest
  samples/package.json
  samples/test/kms.test.js
Labels: cla: yes

#329 fix: regen protos and tests, fix formatting
  synth.metadata
  test/gapic_key_management_service_v1.ts
Labels: automerge, cla: yes

#330 fix: synth.py clean up for multiple version
  src/index.ts
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#331 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
