Repository googleapis/nodejs-kms, pull requests merged in 2020-11, with the labels that each got.

#397 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full

#398 build: add v1.KeyManagementServiceClient type
  src/index.ts
  synth.metadata
Labels: api: cloudkms, cla: yes, context: none

#399 fix: do not modify options object, use defaultScopes
  package.json
  src/v1/key_management_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: cloudkms, automerge, cla: yes

#401 chore: give api-kms team push access
  .github/sync-repo-settings.yaml
Labels: api: cloudkms, cla: yes

#404 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/key_management_service_client.ts
  synth.metadata
Labels: api: cloudkms, cla: yes, context: partial

#406 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: cloudkms, automerge, cla: yes, context: full
